Handle conflict

diff --git a/.github/workflows/downmerge2.yml b/.github/workflows/downmerge2.yml
--- a/.github/workflows/downmerge2.yml
+++ b/.github/workflows/downmerge2.yml
@@ -20,20 +20,28 @@ jobs:
     - name: Create pull request
       run: |
         echo "-----"
-        echo "Creating Merge PR"
+        echo "$ Creating Merge PR"
         url=$(gh pr create -B ${{ env.DEVELOP_BRANCH }} -H ${{ env.MAIN_BRANCH }} --title 'Merge ${{ env.MAIN_BRANCH }} into ${{ env.DEVELOP_BRANCH }}' --body 'Created by Github action')
+        echo "$ PR created: $url"
+        
         echo "-----"
-        echo "PR created: $url"
-        echo "-----"
-        echo "PR Status"
+        echo "$ PR Status"
         gh pr ready $url
-        gh pr status --conflict-status --json mergeable
+        status=$(gh pr status --json mergeable)
+        if echo "$status" | grep -q "CONFLICTING"; then
+            echo "The are conflicts that need to be solved manually"
+            echo "Finishing with error"
+            exit 1
+        fi
+        
         echo "-----"
-        echo "Wait for CI"
-        gh pr checks $url --required --watch
+        echo "$ Wait for CI"
+        gh pr checks $url --watch
+        
         echo "-----"
-        echo "Attempting auto merge"
+        echo "$ Attempting auto merge"
         gh pr merge $url --auto --merge
+        
         echo "-----"
         echo "Done"
       env:
